#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio python3.8 "${APP_DIR}/bazarr.py" --no-update --config "${CONFIG_DIR}/app" ${ARGS}
